ALTER TABLE asset
    ADD COLUMN asset_category VARCHAR(50);

UPDATE asset
SET asset_category = CASE ticker

    -- AÇÕES
    WHEN 'BBAS3' THEN 'BANKING'
    WHEN 'BBSE3' THEN 'INSURANCE'
    WHEN 'TAEE3' THEN 'ELECTRIC_TRANSMISSION'
    WHEN 'RAIZ4' THEN 'ENERGY'

    -- FIIS
    WHEN 'FATN11' THEN 'CORPORATE_OFFICE'
    WHEN 'GARE11' THEN 'URBAN_INCOME'
    WHEN 'XPLG11' THEN 'LOGISTICS'
    WHEN 'VISC11' THEN 'SHOPPING'
    WHEN 'KNHF11' THEN 'MULTI_STRATEGY'
    WHEN 'XPML11' THEN 'SHOPPING'
    WHEN 'GAME11' THEN 'MULTI_STRATEGY'
    WHEN 'TRXF11' THEN 'URBAN_INCOME'
    WHEN 'BIME11' THEN 'MULTI_STRATEGY'
    WHEN 'VGIR11' THEN 'PAPER'
    WHEN 'VIUR11' THEN 'URBAN_INCOME'

    -- FIAGRO
    WHEN 'VGIA11' THEN 'AGRIBUSINESS'

    ELSE 'OTHER'

END;

UPDATE asset
SET asset_type = 'FIAGRO'
WHERE ticker = 'VGIA11';

ALTER TABLE asset
    ALTER COLUMN asset_category SET NOT NULL;

ALTER TABLE asset
    DROP COLUMN segment;